// Registers LiteEditor in the Ubuntu app menu (no sudo — installs into ~/.local).
// Creates a launcher script + a .desktop entry pointing at this checkout.
const path = require('path');
const fs = require('fs');
const os = require('os');

const root = path.join(__dirname, '..');
const home = os.homedir();
const appsDir = path.join(home, '.local', 'share', 'applications');
const launcher = path.join(root, 'lite-editor');

// The Ubuntu app menu launches with a minimal PATH that usually lacks nvm's
// node. electron's shim is `#!/usr/bin/env node`, so we bake node's dir into
// PATH here to make icon-launch work regardless of the GUI session PATH.
const nodeDir = path.dirname(process.execPath);
const electronBin = path.join(root, 'node_modules', '.bin', 'electron');
const logFile = path.join(root, 'lite-editor.log');

const iconPng = path.join(root, 'assets', 'icon.png');
const iconSvg = path.join(root, 'assets', 'icon.svg');
const icon = fs.existsSync(iconPng) ? iconPng : iconSvg;

const launcherBody = `#!/usr/bin/env bash
# Auto-generated by scripts/install-desktop.js — do not edit by hand.
export PATH="${nodeDir}:$PATH"
cd "${root}" || exit 1
node build.js || echo "[build.js упал — открываю прошлую сборку]"
# --class задаёт WM_CLASS окна = StartupWMClass из .desktop, иначе WM не свяжет
# запущенное окно с ярлыком и покажет обобщённую иконку (шестерёнку).
exec "${electronBin}" --no-sandbox --class=LiteEditorAI . "$@" > "${logFile}" 2>&1
`;

const desktopBody = `[Desktop Entry]
Type=Application
Name=LiteEditorAI
GenericName=AI Agent Editor
Comment=Лёгкий редактор для работы с ИИ-агентами в терминале
Exec=${launcher} %U
Icon=${icon}
Terminal=false
Categories=Development;Utility;TextEditor;
StartupNotify=true
StartupWMClass=LiteEditorAI
`;

fs.writeFileSync(launcher, launcherBody, { mode: 0o755 });
fs.mkdirSync(appsDir, { recursive: true });
const desktopPath = path.join(appsDir, 'lite-editor.desktop');
fs.writeFileSync(desktopPath, desktopBody);

console.log('Launcher:  ' + launcher);
console.log('Desktop:   ' + desktopPath);
console.log('Готово. LiteEditor должен появиться в меню приложений Ubuntu.');
console.log('Если иконка не подтянулась сразу — перелогинься или: update-desktop-database ~/.local/share/applications');
