// Registers LiteEditor in the Ubuntu app menu (no sudo — installs into ~/.local).
// Creates a launcher script + a .desktop entry pointing at this checkout.
const path = require('path');
const fs = require('fs');
const os = require('os');
const { execFileSync } = require('child_process');

const root = path.join(__dirname, '..');
const home = os.homedir();
const appsDir = path.join(home, '.local', 'share', 'applications');
const launcher = path.join(root, 'lite-editor');

// The Ubuntu app menu launches with a minimal PATH that usually lacks nvm's
// node. electron's shim is `#!/usr/bin/env node`, so we bake node's dir into
// PATH here to make icon-launch work regardless of the GUI session PATH.
const nodeDir = path.dirname(process.execPath);
const electronBin = path.join(root, 'node_modules', '.bin', 'electron');

const iconPng = path.join(root, 'assets', 'icon.png');
const iconSvg = path.join(root, 'assets', 'icon.svg');

// ⚠️ WM_CLASS окна = `name` из package.json (= 'liteeditor-ai'). Electron 42 (Ozone/X11)
// ИГНОРИРУЕТ `--class`, поэтому привязка ярлыка к окну (StartupWMClass) и имя иконки в теме
// должны совпадать именно с 'liteeditor-ai', иначе GNOME покажет обобщённую шестерёнку.
const WM_CLASS = require(path.join(root, 'package.json')).name; // 'liteeditor-ai'

// Иконку ставим и в тему hicolor под именем = WM_CLASS — так GNOME находит иконку окна
// по WM_CLASS, даже если ассоциация с .desktop на миг не сработала. Ссылаемся на неё ПО ИМЕНИ.
let iconRef = fs.existsSync(iconPng) ? iconPng : iconSvg; // фолбэк — абсолютный путь
if (fs.existsSync(iconPng)) {
  try {
    for (const sz of ['256x256', '512x512']) {
      const dir = path.join(home, '.local', 'share', 'icons', 'hicolor', sz, 'apps');
      fs.mkdirSync(dir, { recursive: true });
      fs.copyFileSync(iconPng, path.join(dir, `${WM_CLASS}.png`));
    }
    iconRef = WM_CLASS; // themed icon name — надёжнее абсолютного пути в доке GNOME
  } catch (_) { /* нет прав/темы — останемся на абсолютном пути */ }
}

const launcherBody = `#!/usr/bin/env bash
# Auto-generated by scripts/install-desktop.js — do not edit by hand.
export PATH="${nodeDir}:$PATH"
cd "${root}" || exit 1
# Append all output (build + Electron native stderr) to a dated log next to the
# store so a crash isn't wiped by the next launch; logger.js prunes >5 days.
LOGDIR="$HOME/.LiteEditorAI/logs"; mkdir -p "$LOGDIR"
exec >> "$LOGDIR/launch-$(date +%F).log" 2>&1
echo "=== launch $(date '+%F %T') ==="
node build.js || echo "[build.js упал — открываю прошлую сборку]"
# --class совпадает с WM_CLASS (= package.json name) и StartupWMClass в .desktop. Electron 42
# его игнорирует и берёт WM_CLASS из name, но держим в согласии на случай других окружений.
exec "${electronBin}" --no-sandbox --class=${WM_CLASS} . "$@"
`;

const desktopBody = `[Desktop Entry]
Type=Application
Name=LiteEditorAI
GenericName=AI Agent Editor
Comment=Лёгкий редактор для работы с ИИ-агентами в терминале
Exec=${launcher} %U
Icon=${iconRef}
Terminal=false
Categories=Development;Utility;TextEditor;
StartupNotify=true
StartupWMClass=${WM_CLASS}
`;

fs.writeFileSync(launcher, launcherBody, { mode: 0o755 });
fs.mkdirSync(appsDir, { recursive: true });
const desktopPath = path.join(appsDir, 'lite-editor.desktop');
fs.writeFileSync(desktopPath, desktopBody);

// Освежить кэши тем/ярлыков (best-effort — отсутствие утилит не критично).
const quiet = { stdio: 'ignore' };
try { execFileSync('gtk-update-icon-cache', ['-f', '-t', path.join(home, '.local', 'share', 'icons', 'hicolor')], quiet); } catch (_) {}
try { execFileSync('update-desktop-database', [appsDir], quiet); } catch (_) {}

console.log('Launcher:  ' + launcher);
console.log('Desktop:   ' + desktopPath);
console.log('Icon:      ' + iconRef + '  (WM_CLASS=' + WM_CLASS + ')');
console.log('Готово. LiteEditor должен появиться в меню приложений Ubuntu.');
console.log('Если иконка не подтянулась сразу — перелогинься или: update-desktop-database ~/.local/share/applications');
